name: Analyze & Test

on:
  push:
  workflow_dispatch:

jobs:
  analyze:
    name: Analyze
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v7
        with:
          fetch-depth: 0

      - name: Setup flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable
          flutter-version-file: pubspec.yaml

      - name: Apply SDK patches
        shell: pwsh
        run: lib/scripts/patch.ps1

      - name: Analyze
        run: flutter analyze --no-fatal-infos --no-fatal-warnings

  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v7
        with:
          fetch-depth: 0

      - name: Setup flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable
          flutter-version-file: pubspec.yaml

      - name: Apply SDK patches
        shell: pwsh
        run: lib/scripts/patch.ps1

      - name: Test
        run: flutter test
